server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HotelDatabase
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: HOTEL-SERVICE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
