server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AuthorizationDatabase
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: AUTHORIZATION-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
