server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserDatabase
    username: root
    password: root


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




