server:
  port: 8084

spring:
  application:
    name: API-GATEWAY



  cloud:
    gateway:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**
            filters:
              - AuthenticationFilter

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/ratings/**
            filters:
              - AuthenticationFilter

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/hotels/** ,/staffs/**
            filters:
              - AuthenticationFilter

          - id: AUTHORIZATION-SERVICE
            uri: lb://AUTHORIZATION-SERVICE
            predicates:
              - Path=/auth/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka